- name: Demo on play level variables
  hosts: all
  vars: 
    URL: play.example.com
  tasks: 
    - name: print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}

# vars is the key we are using and -name: demo.... is something we can give or escape as our wish
# in ansible variables will be accessed using {{}}
#  ansible supports "" and '' however quotes are not mandotroy in all cases
# but quotes are mandatory if value starts with a variable
# example for that is - msg: {{}} ---> this doesnt require quoting
# msg -URL - {{ URL }} ----> this doesnt require quoting

# if we declare a variable on the play level, all the taskes can access that variable.
# if we declare a variable on the task level, then only that tasks will be able to access

- name: Demo on play level variables
  hosts: all
  tasks: 
    - name: print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}
      vars: 
        URL: task.example.com
